# Generated by Django 2.1.4 on 2018-12-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('position', models.CharField(db_index=True, max_length=150)),
                ('emp_date', models.DateField(db_index=True)),
                ('salary', models.IntegerField(db_index=True)),
            ],
        ),
    ]
