# Generated by Django 2.1.4 on 2019-01-01 15:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.Employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default='1.jpg', upload_to='empl_photo'),
        ),
    ]
