# Generated by Django 2.1.4 on 2019-01-01 15:48

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_auto_20190101_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree.Employees'),
        ),
    ]
